import { ArrowDown, ArrowRight, ArrowUp, Check, Circle, Diamond, Eraser, ImagePlus, LineChart, MousePointer2, PaintBucket, Pencil, PenLine, Plus, RectangleHorizontal, Undo2, X, ZoomIn, ZoomOut } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { formatBytes } from '../lib/format'
import type { CanvasImage, CanvasPoint, CanvasSession, CanvasShape, CanvasStroke, CanvasTraffic } from '../hooks/useBeam'

type Tool = CanvasShape | 'pan' | 'eraser' | 'fill'
type Props = { canvas: CanvasSession; traffic: CanvasTraffic; displayName: string; onClose(): void; onRename(name: string): void; onStroke(stroke: CanvasStroke): void; onImage(image: CanvasImage): void; onDelete(id: string): void }
const uid = () => crypto.randomUUID?.().replaceAll('-', '_') ?? `${Date.now()}_${Math.random()}`
const colors = ['#1f2937', '#4f46e5', '#dc2626', '#059669', '#d97706']
const tools: { id: Tool; label: string; icon: typeof Pencil }[] = [{ id: 'freehand', label: 'Draw', icon: Pencil }, { id: 'line', label: 'Line', icon: LineChart }, { id: 'arrow', label: 'Arrow', icon: ArrowRight }, { id: 'rectangle', label: 'Rectangle', icon: RectangleHorizontal }, { id: 'ellipse', label: 'Ellipse', icon: Circle }, { id: 'diamond', label: 'Diamond', icon: Diamond }, { id: 'eraser', label: 'Eraser', icon: Eraser }, { id: 'pan', label: 'Pan', icon: MousePointer2 }]
const box = (points: CanvasPoint[]) => { const [a, b = a] = points; return { x: Math.min(a.x, b.x), y: Math.min(a.y, b.y), width: Math.abs(b.x - a.x), height: Math.abs(b.y - a.y) } }

function CanvasMark({ stroke }: { stroke: CanvasStroke }) {
  const shape = stroke.shape ?? 'freehand', points = stroke.points, end = points.at(-1)
  if (!points.length || !end) return null
  const common = { stroke: stroke.color, strokeWidth: stroke.width, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, vectorEffect: 'non-scaling-stroke' as const }
  if (shape === 'freehand') return points.length === 1 ? <circle cx={end.x} cy={end.y} r={stroke.width / 2} fill={stroke.color} /> : <polyline points={points.map(point => `${point.x},${point.y}`).join(' ')} fill="none" {...common} />
  if (shape === 'line' || shape === 'arrow') return <line x1={points[0].x} y1={points[0].y} x2={end.x} y2={end.y} markerEnd={shape === 'arrow' ? 'url(#canvas-arrow)' : undefined} {...common} />
  const bounds = box(points), fill = stroke.fill ?? 'none'
  if (shape === 'rectangle') return <rect x={bounds.x} y={bounds.y} width={bounds.width} height={bounds.height} rx={4} fill={fill} {...common} />
  if (shape === 'ellipse') return <ellipse cx={bounds.x + bounds.width / 2} cy={bounds.y + bounds.height / 2} rx={bounds.width / 2} ry={bounds.height / 2} fill={fill} {...common} />
  return <polygon points={`${bounds.x + bounds.width / 2},${bounds.y} ${bounds.x + bounds.width},${bounds.y + bounds.height / 2} ${bounds.x + bounds.width / 2},${bounds.y + bounds.height} ${bounds.x},${bounds.y + bounds.height / 2}`} fill={fill} {...common} />
}

export function CanvasBoard({ canvas, traffic, displayName, onClose, onRename, onStroke, onImage, onDelete }: Props) {
  const stage = useRef<HTMLDivElement>(null), imageInput = useRef<HTMLInputElement>(null), activeStroke = useRef<CanvasPoint[]>([]), strokeId = useRef<string | null>(null), lastBroadcast = useRef(0)
  const [tool, setTool] = useState<Tool>('freehand'), [color, setColor] = useState(colors[0]), [width, setWidth] = useState(3), [zoom, setZoom] = useState(1), [offset, setOffset] = useState({ x: 0, y: 0 }), [draft, setDraft] = useState<CanvasStroke | null>(null), [dragStart, setDragStart] = useState<{ x: number; y: number; offset: { x: number; y: number } } | null>(null), [status, setStatus] = useState(''), [renaming, setRenaming] = useState(false), [nameDraft, setNameDraft] = useState(canvas.name)
  const canRename = canvas.starter === displayName, drawingTool = !['pan', 'eraser', 'fill'].includes(tool)
  const saveName = () => { const next = nameDraft.trim(); if (next) onRename(next); setRenaming(false) }
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.target as HTMLElement)?.matches('input, textarea, select')) return; if (event.key === 'Escape') onClose(); if (event.key.toLowerCase() === 'v') setTool('pan'); if (event.key.toLowerCase() === 'd') setTool('freehand'); if (event.key.toLowerCase() === 'e') setTool('eraser'); if (event.key.toLowerCase() === 'f') setTool('fill'); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); const last = [...canvas.strokes].reverse().find(stroke => stroke.author === displayName); if (last) onDelete(last.id) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [canvas.strokes, displayName, onClose, onDelete])
  useEffect(() => { const onPaste = (event: ClipboardEvent) => { const file = [...(event.clipboardData?.files ?? [])].find(item => item.type.startsWith('image/')); if (!file) return; event.preventDefault(); void compressAndAdd(file) }; window.addEventListener('paste', onPaste); return () => window.removeEventListener('paste', onPaste) })
  const toCanvasPoint = (event: React.PointerEvent) => { const rect = stage.current!.getBoundingClientRect(); return { x: (event.clientX - rect.left - offset.x) / zoom, y: (event.clientY - rect.top - offset.y) / zoom } }
  const eraseAt = (point: CanvasPoint) => { const target = [...canvas.strokes].reverse().find(stroke => { const bounds = box(stroke.points), pad = 14 + stroke.width; return point.x >= bounds.x - pad && point.x <= bounds.x + bounds.width + pad && point.y >= bounds.y - pad && point.y <= bounds.y + bounds.height + pad }); if (target) { onDelete(target.id); setStatus('Element removed.') } }
  const contains = (stroke: CanvasStroke, point: CanvasPoint) => { const shape = stroke.shape; if (!shape || !['rectangle', 'ellipse', 'diamond'].includes(shape)) return false; const bounds = box(stroke.points); if (!bounds.width || !bounds.height) return false; const x = (point.x - bounds.x) / bounds.width, y = (point.y - bounds.y) / bounds.height; if (shape === 'rectangle') return x >= 0 && x <= 1 && y >= 0 && y <= 1; if (shape === 'ellipse') return (x - .5) ** 2 / .25 + (y - .5) ** 2 / .25 <= 1; return Math.abs(x - .5) + Math.abs(y - .5) <= .5 }
  const fillAt = (point: CanvasPoint) => { const target = [...canvas.strokes].reverse().find(stroke => contains(stroke, point)); if (!target) { setStatus('Tap inside a rectangle, ellipse, or diamond to fill it.'); return }; onStroke({ ...target, fill: color }); setStatus('Shape filled.') }
  const publishStroke = (points: CanvasPoint[], broadcast = true) => { const stroke = { id: strokeId.current ?? uid(), points, color, width, author: displayName, shape: tool as CanvasShape }; strokeId.current = stroke.id; setDraft(stroke); if (broadcast) onStroke(stroke) }
  const finishStroke = () => { const points = activeStroke.current; if (points.length && drawingTool) publishStroke(points); activeStroke.current = []; strokeId.current = null; setDraft(null) }
  const pointerDown = (event: React.PointerEvent<HTMLDivElement>) => { event.currentTarget.setPointerCapture(event.pointerId); if (tool === 'pan' || event.button === 1 || event.button === 2) { setDragStart({ x: event.clientX, y: event.clientY, offset }); return }; const point = toCanvasPoint(event); if (tool === 'eraser') { eraseAt(point); return }; if (tool === 'fill') { fillAt(point); return }; activeStroke.current = [point]; strokeId.current = uid(); lastBroadcast.current = performance.now(); publishStroke(activeStroke.current, false) }
  const pointerMove = (event: React.PointerEvent<HTMLDivElement>) => { if (dragStart) { setOffset({ x: dragStart.offset.x + event.clientX - dragStart.x, y: dragStart.offset.y + event.clientY - dragStart.y }); return }; if (!activeStroke.current.length || !drawingTool) return; const point = toCanvasPoint(event), last = activeStroke.current.at(-1)!; if (tool === 'freehand') { if (Math.hypot(point.x - last.x, point.y - last.y) < 1.5) return; activeStroke.current = [...activeStroke.current, point] } else activeStroke.current = [activeStroke.current[0], point]; const now = performance.now(); publishStroke(activeStroke.current, now - lastBroadcast.current >= 55); if (now - lastBroadcast.current >= 55) lastBroadcast.current = now }
  const compressAndAdd = async (file: File) => { if (!file.type.startsWith('image/')) { setStatus('Choose an image file.'); return }; setStatus('Compressing image…'); try { const source = await createImageBitmap(file), scale = Math.min(1, 1280 / Math.max(source.width, source.height)), imageWidth = Math.max(1, Math.round(source.width * scale)), imageHeight = Math.max(1, Math.round(source.height * scale)), output = document.createElement('canvas'); output.width = imageWidth; output.height = imageHeight; output.getContext('2d')!.drawImage(source, 0, 0, imageWidth, imageHeight); source.close(); const blob = await new Promise<Blob | null>(resolve => output.toBlob(resolve, 'image/webp', .72)); if (!blob || blob.size > 950_000) { setStatus('Image is still too large after compression.'); return }; const dataUrl = await new Promise<string>(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(blob) }); onImage({ id: uid(), dataUrl, x: 80 - offset.x / zoom, y: 80 - offset.y / zoom, width: imageWidth, height: imageHeight, author: displayName }); setStatus(`Image added · ${Math.round(blob.size / 1024)} KB`) } catch { setStatus('Could not add that image. Try another file.') } }
  const shownStrokes = draft ? [...canvas.strokes.filter(stroke => stroke.id !== draft.id), draft] : canvas.strokes
  const undo = () => { const last = [...canvas.strokes].reverse().find(stroke => stroke.author === displayName); if (last) onDelete(last.id) }
  return <section className="canvas-board" aria-label="Collaborative canvas">
    <header className="canvas-board__head"><div className="canvas-board__title"><div className="canvas-board__name-row">{renaming ? <><input aria-label="Canvas name" autoFocus value={nameDraft} maxLength={80} onChange={event => setNameDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') saveName(); if (event.key === 'Escape') setRenaming(false) }} /><button type="button" className="canvas-board__rename" onClick={saveName}><Check size={18} /> Save</button></> : <><strong>{canvas.name}</strong>{canRename && <button type="button" className="canvas-board__rename" onClick={() => { setNameDraft(canvas.name); setRenaming(true) }} aria-label="Rename canvas"><PenLine size={16} /></button>}</>}</div><span>Shared canvas</span></div><div className="canvas-board__actions"><div className="canvas-board__traffic" title="Canvas sync traffic" aria-label={`Canvas data: ${formatBytes(traffic.sent)} sent and ${formatBytes(traffic.received)} received`}><ArrowUp size={13} />{formatBytes(traffic.sent)} <ArrowDown size={13} />{formatBytes(traffic.received)}</div><button type="button" className="canvas-board__close" onClick={onClose} aria-label="Close canvas"><X size={19} /></button></div></header>
    <div className="canvas-board__toolbar" role="toolbar" aria-label="Canvas tools"><div className="canvas-board__tool-group canvas-board__tool-group--drawing">{tools.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={tool === id ? 'is-active' : ''} onClick={() => setTool(id)} aria-label={label} aria-pressed={tool === id} title={label}><Icon size={18} /><span>{label}</span></button>)}</div><div className="canvas-board__tool-group canvas-board__tool-group--style"><button type="button" className={tool === 'fill' ? 'is-active' : ''} onClick={() => setTool('fill')} aria-label="Fill existing shape" aria-pressed={tool === 'fill'} title="Fill existing shape"><PaintBucket size={18} /><span>Fill</span></button>{colors.map(value => <button key={value} type="button" className={`canvas-board__color ${color === value ? 'is-active' : ''}`} style={{ '--swatch': value } as React.CSSProperties} onClick={() => setColor(value)} aria-label={`Use ${value} color`} aria-pressed={color === value} />)}<label className="canvas-board__custom-color" title="Custom color"><span>Custom color</span><Plus size={18} aria-hidden="true" /><input type="color" value={color} onChange={event => setColor(event.target.value)} aria-label="Choose color" /></label><label className="canvas-board__width" title="Stroke width"><span>Width</span><input aria-label="Stroke width" type="range" min="2" max="14" value={width} onChange={event => setWidth(Number(event.target.value))} /></label></div><div className="canvas-board__tool-group canvas-board__tool-group--actions"><button type="button" onClick={() => imageInput.current?.click()} aria-label="Add image" title="Add image"><ImagePlus size={18} /><span>Image</span></button><button type="button" onClick={undo} aria-label="Undo your last element" title="Undo"><Undo2 size={18} /></button><button type="button" onClick={() => setZoom(value => Math.max(.35, value - .15))} aria-label="Zoom out"><ZoomOut size={18} /></button><button type="button" onClick={() => setZoom(value => Math.min(2.5, value + .15))} aria-label="Zoom in"><ZoomIn size={18} /></button></div></div>
    <input ref={imageInput} className="sr-only" type="file" accept="image/*" onChange={event => { const file = event.target.files?.[0]; if (file) void compressAndAdd(file); event.currentTarget.value = '' }} />
    <div ref={stage} className={`canvas-board__stage canvas-board__stage--${tool}`} onContextMenu={event => event.preventDefault()} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={() => { setDragStart(null); finishStroke() }} onPointerCancel={() => { setDragStart(null); finishStroke() }}><svg className="canvas-board__drawing" aria-label="Shared drawing surface"><defs><marker id="canvas-arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="context-stroke" /></marker></defs><g transform={`translate(${offset.x} ${offset.y}) scale(${zoom})`}>{canvas.images.map(image => <image key={image.id} href={image.dataUrl} x={image.x} y={image.y} width={image.width} height={image.height} preserveAspectRatio="xMidYMid meet" />)}{shownStrokes.map(stroke => <CanvasMark key={stroke.id} stroke={stroke} />)}</g></svg>{!canvas.strokes.length && !canvas.images.length && <div className="canvas-board__hint"><Pencil size={22} /><strong>Start with a simple idea</strong><span>Draw, add a shape, or paste an image.</span></div>}</div>
    <footer className="canvas-board__foot"><span>{status || 'Everything syncs directly with the people in this Beam.'}</span><span>Draw D · Pan V · Fill F · Erase E</span></footer>
  </section>
}
