import { AnimatePresence, motion } from 'framer-motion'
import { Check, Clipboard, Copy, FileText, Link2, LoaderCircle, LogOut, Plus, QrCode, Send, Upload, WifiOff, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import QRCode from 'qrcode'
import { generatePassphrase, isValidSecret, normalizeSecret } from './lib/codes'
import { formatBytes, hostnameFor, isUrl } from './lib/format'
import { defaultDisplayName } from './lib/device'
import { useBeam, type FeedItem, type TransferRecord } from './hooks/useBeam'

type View = { mode: 'home' } | { mode: 'waiting'; secret: string } | { mode: 'room'; secret: string }
function route(): View { const match = location.hash.match(/^#\/join\/(.+)$/); return match ? { mode: 'waiting', secret: decodeURIComponent(match[1]) } : { mode: 'home' } }

function Logo() {
  return <svg className="beam-logo" viewBox="0 0 178 40" aria-hidden="true">
    <text className="beam-logo__beam" x="0" y="30">beam</text>
    <text className="beam-logo__drop" x="88" y="30">Drop</text>
    <circle className="beam-logo__dot" cx="169" cy="26" r="4" />
  </svg>
}

export function App() {
  const [view, setView] = useState<View>(route)
  const [displayName, setDisplayName] = useState(() => localStorage.getItem('beam:display-name') || defaultDisplayName())
  const [online, setOnline] = useState(navigator.onLine)
  useEffect(() => { const sync = () => setOnline(navigator.onLine); addEventListener('online', sync); addEventListener('offline', sync); return () => { removeEventListener('online', sync); removeEventListener('offline', sync) } }, [])
  const go = (next: View) => { setView(next); location.hash = next.mode === 'home' ? '' : `/join/${encodeURIComponent(next.secret)}` }
  return <main className="app-shell"><header className="topbar"><button className="wordmark" onClick={() => go({ mode: 'home' })} aria-label="Beam home"><Logo /></button><span className="privacy-note">Private, peer-to-peer sharing</span></header>{!online && <div className="offline"><WifiOff size={16} /> You’re offline. Beam needs internet to connect.</div>}<AnimatePresence mode="wait">{view.mode === 'home' ? <Home key="home" onCreate={secret => go({ mode: 'waiting', secret })} onJoin={secret => go({ mode: 'waiting', secret })} /> : <BeamSession key={view.secret} secret={view.secret} displayName={displayName} onRename={name => { setDisplayName(name); localStorage.setItem('beam:display-name', name) }} onEnd={() => go({ mode: 'home' })} />}</AnimatePresence></main>
}

function Home({ onCreate, onJoin }: { onCreate(secret: string): void; onJoin(secret: string): void }) {
  const [join, setJoin] = useState('')
  return <motion.section className="home" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }}><div className="hero"><h1>Send directly.</h1><p className="subhead">Share files, notes, and links with another device. Nothing is uploaded or stored.</p></div><div className="home-actions"><div className="create-panel"><h2>Start a private Beam</h2><p>A secure share link is created instantly.</p><button className="primary create-button" onClick={() => onCreate(generatePassphrase())}>Create Beam <Plus size={18} /></button></div><div className="join-panel"><h2>Join a Beam</h2><div className="join-form"><input aria-label="Beam code or passphrase" value={join} onChange={event => setJoin(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && isValidSecret(join)) onJoin(normalizeSecret(join)) }} placeholder="Enter a code or phrase" /><button className="primary" disabled={!isValidSecret(join)} onClick={() => onJoin(normalizeSecret(join))}>Join</button></div></div></div></motion.section>
}

function BeamSession({ secret, displayName, onRename, onEnd }: { secret: string; displayName: string; onRename(name: string): void; onEnd(): void }) {
  const beam = useBeam(secret, displayName); const [qrOpen, setQrOpen] = useState(false); const [copied, setCopied] = useState(false); const [composer, setComposer] = useState(''); const [showComposer, setShowComposer] = useState(false); const fileInput = useRef<HTMLInputElement>(null)
  const connected = beam.state === 'connected'; const recipient = beam.peers[0]?.name ?? 'your other device'
  const copy = async () => { await navigator.clipboard.writeText(secret); setCopied(true); setTimeout(() => setCopied(false), 1600) }
  if (!connected) return <Waiting secret={secret} state={beam.state} peers={beam.peers.length} onCopy={copy} copied={copied} onQr={() => setQrOpen(true)} onEnd={onEnd} qrOpen={qrOpen} closeQr={() => setQrOpen(false)} />
  return <motion.section className="room" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="room-head"><div><p className="eyebrow">Your Beam</p><h1>Connected to <span>{recipient}</span><i /></h1></div><button className="end-button" onClick={onEnd}><LogOut size={16} /> End Beam</button></div><div className="identity"><span className="device-dot" /><input aria-label="Your display name" value={displayName} onChange={event => onRename(event.target.value.slice(0, 48))} /><span>is visible to connected devices</span></div><DropZone onFiles={files => files.forEach(beam.offerFile)} onPick={() => fileInput.current?.click()} /><input ref={fileInput} className="sr-only" type="file" multiple onChange={event => Array.from(event.target.files ?? []).forEach(beam.offerFile)} /><div className="share-row"><button className="share-action" onClick={() => fileInput.current?.click()}><Upload size={19} /><span>File</span></button><button className="share-action" onClick={() => setShowComposer(!showComposer)}><FileText size={19} /><span>Text</span></button><button className="share-action" onClick={() => { setShowComposer(true); setComposer('https://') }}><Link2 size={19} /><span>Link</span></button><button className="share-action disabled" title="Coming next"><Clipboard size={19} /><span>Paste</span></button></div><AnimatePresence>{showComposer && <motion.form className="composer" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} onSubmit={event => { event.preventDefault(); beam.sendItem(composer, isUrl(composer) ? 'link' : 'text'); setComposer(''); setShowComposer(false) }}><textarea autoFocus value={composer} onChange={event => setComposer(event.target.value)} placeholder="Share a note or paste a link…" /><button className="primary" disabled={!composer.trim()} type="submit">Send <Send size={16} /></button></motion.form>}</AnimatePresence><div className="room-grid"><section><h2>Transfers</h2><div className="transfer-list"><AnimatePresence>{beam.transfers.length ? beam.transfers.map(transfer => <TransferCard key={transfer.id} item={transfer} recipient={recipient} onAccept={() => beam.replyToOffer(transfer.id, true)} onDecline={() => beam.replyToOffer(transfer.id, false)} onCancel={() => beam.cancelTransfer(transfer.id)} />) : <p className="empty">Files you send and receive will appear here.</p>}</AnimatePresence></div></section><section><h2>Recent</h2><div className="feed">{beam.feed.length ? beam.feed.map(item => <FeedCard key={item.id} item={item} />) : <p className="empty">Your Beam is ready. Send something to get started.</p>}</div></section></div></motion.section>
}

function Waiting({ secret, state, peers, onCopy, copied, onQr, onEnd, qrOpen, closeQr }: { secret: string; state: string; peers: number; onCopy(): void; copied: boolean; onQr(): void; onEnd(): void; qrOpen: boolean; closeQr(): void }) { const label = state === 'failed' ? "Couldn't establish a connection." : state === 'disconnected' ? 'Connection lost. Waiting to reconnect…' : peers ? 'Device found. Establishing secure connection…' : 'Waiting for someone to join…'; return <motion.section className="waiting" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="beam-card"><p className="eyebrow">Your Beam</p><h1>{secret}</h1><div className="waiting-actions"><button onClick={onCopy}>{copied ? <Check size={17} /> : <Copy size={17} />}{copied ? 'Copied' : 'Copy'}</button><button onClick={onQr}><QrCode size={17} /> QR</button></div><div className={`connection ${state}`}><LoaderCircle size={19} /><div><strong>{label}</strong><p>Share this code or scan the QR code on another device.</p></div></div></div><button className="text-button end-link" onClick={onEnd}>Cancel and return home</button>{qrOpen && <QrDialog secret={secret} onClose={closeQr} />}</motion.section> }

function DropZone({ onFiles, onPick }: { onFiles(files: File[]): void; onPick(): void }) { const [over, setOver] = useState(false); return <div className={`dropzone ${over ? 'over' : ''}`} onDragOver={event => { event.preventDefault(); setOver(true) }} onDragLeave={() => setOver(false)} onDrop={event => { event.preventDefault(); setOver(false); onFiles(Array.from(event.dataTransfer.files)) }}><div className="drop-icon"><Upload size={24} /></div><h2>{over ? 'Drop to Beam' : 'Drop anything here'}</h2><p>or <button onClick={onPick}>choose files</button> from this device</p><span>Sent directly to your connected device</span></div> }

function TransferCard({ item, recipient, onAccept, onDecline, onCancel }: { item: TransferRecord; recipient: string; onAccept(): void; onDecline(): void; onCancel(): void }) { const needsReply = item.direction === 'receiving' && item.status === 'offered'; return <motion.article className="transfer-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="file-mark"><FileText size={19} /></div><div className="transfer-main"><div className="transfer-title"><strong title={item.name}>{item.name}</strong><span>{formatBytes(item.size)} · {item.direction === 'sending' ? `To ${recipient}` : `From ${item.sender}`}</span></div>{needsReply ? <div className="offer-buttons"><button className="quiet-button" onClick={onDecline}>Decline</button><button className="primary small" onClick={onAccept}>Accept</button></div> : <><div className="progress"><i style={{ width: `${item.progress * 100}%` }} /></div><div className="transfer-meta"><span>{item.status === 'complete' ? 'Complete' : item.status === 'declined' ? 'Declined' : item.status === 'cancelled' ? 'Cancelled' : `${Math.round(item.progress * 100)}% · ${formatBytes(item.speed)}/s`}</span>{['offered', 'active'].includes(item.status) && <button onClick={onCancel}>Cancel</button>}</div></>}</div></motion.article> }

function FeedCard({ item }: { item: FeedItem }) { return <article className="feed-item"><div className="feed-icon">{item.kind === 'file' ? <FileText size={17} /> : item.kind === 'link' ? <Link2 size={17} /> : <FileText size={17} />}</div><div><strong>{item.kind === 'link' ? hostnameFor(item.value) : item.value}</strong><span>From {item.sender}{item.size ? ` · ${formatBytes(item.size)}` : ''}</span></div>{item.kind === 'file' && item.objectUrl ? <a href={item.objectUrl} download={item.value}>Save</a> : item.kind === 'link' ? <a href={item.value} target="_blank" rel="noreferrer">Open</a> : <button onClick={() => void navigator.clipboard.writeText(item.value)}>Copy</button>}</article> }

function QrDialog({ secret, onClose }: { secret: string; onClose(): void }) { const [dataUrl, setDataUrl] = useState(''); const joinUrl = useMemo(() => `${location.origin}${location.pathname}#/join/${encodeURIComponent(secret)}`, [secret]); useEffect(() => { void QRCode.toDataURL(joinUrl, { width: 260, margin: 1, color: { dark: '#111827', light: '#ffffff' } }).then(setDataUrl) }, [joinUrl]); return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><div className="qr-dialog" role="dialog" aria-modal="true" aria-label="Beam QR code" onMouseDown={event => event.stopPropagation()}><button className="close" onClick={onClose} aria-label="Close"><X size={18} /></button><p className="eyebrow">Scan to join</p><h2>Open this Beam on another device</h2>{dataUrl && <img src={dataUrl} alt={`QR code to join Beam ${secret}`} />}<p>{secret}</p></div></div> }
